
import React from 'react';
import { User, UserRole, Certificate } from './types';
import { BADGES, ACHIEVEMENTS } from './constants';
import { jsPDF } from 'jspdf';

interface ProfileViewProps {
  user: User;
  onLogout: () => void;
  onNavigate?: (tab: string) => void; // NEW: Navigation callback
}

const ProfileView: React.FC<ProfileViewProps> = ({ user, onLogout, onNavigate }) => {
  const [stats, setStats] = React.useState({
    totalStudents: 0,
    totalWords: 0,
    activeStudents: 0,
    avgClassProgress: 0,
    wordsCreated: 0,
    totalGamesPlayed: 0
  });
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {
    if (user.role === UserRole.TEACHER) {
      loadTeacherStats();
    }
  }, [user]);

  const loadTeacherStats = async () => {
    try {
      const { getAllStudents, getWords } = await import('./firebaseService');
      const [students, words] = await Promise.all([
        getAllStudents(),
        getWords()
      ]);

      const activeStudents = students.filter(s => (s.totalGames || 0) > 0).length;
      const totalGames = students.reduce((sum, s) => sum + (s.totalGames || 0), 0);
      const avgProgress = students.length > 0
        ? Math.round(
            students.reduce((sum, s) => {
              const progress = s.levelProgress
                ? Object.values(s.levelProgress).reduce((pSum: number, lp: any) => pSum + lp.mastery, 0) / 3
                : 0;
              return sum + progress;
            }, 0) / students.length
          )
        : 0;

      // Count words created by this teacher (if createdBy field exists)
      const wordsCreated = words.filter(w => w.createdBy === user.id).length;

      setStats({
        totalStudents: students.length,
        totalWords: words.length,
        activeStudents,
        avgClassProgress: avgProgress,
        wordsCreated,
        totalGamesPlayed: totalGames
      });
    } catch (error) {
      console.error('Error loading teacher stats:', error);
    } finally {
      setLoading(false);
    }
  };

  const generateClassReport = async () => {
    try {
      const { getAllStudents } = await import('./firebaseService');
      const students = await getAllStudents();

      const doc = new jsPDF();
      
      // Header
      doc.setFontSize(20);
      doc.setTextColor(0, 194, 160);
      doc.text('Class Performance Report', 105, 20, { align: 'center' });
      
      // Teacher Info
      doc.setFontSize(12);
      doc.setTextColor(0, 0, 0);
      doc.text(`Teacher: ${user.name}`, 20, 35);
      doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 42);
      doc.text(`Total Students: ${stats.totalStudents}`, 20, 49);
      
      // Statistics
      doc.setFontSize(14);
      doc.setTextColor(0, 194, 160);
      doc.text('Class Statistics', 20, 65);
      
      doc.setFontSize(11);
      doc.setTextColor(0, 0, 0);
      doc.text(`Active Students: ${stats.activeStudents} (${Math.round((stats.activeStudents / stats.totalStudents) * 100)}%)`, 20, 75);
      doc.text(`Average Class Mastery: ${stats.avgClassProgress}%`, 20, 82);
      doc.text(`Total Words in Bank: ${stats.totalWords}`, 20, 89);
      doc.text(`Words Created by You: ${stats.wordsCreated}`, 20, 96);
      doc.text(`Total Games Played: ${stats.totalGamesPlayed}`, 20, 103);
      
      // Student List
      doc.setFontSize(14);
      doc.setTextColor(0, 194, 160);
      doc.text('Student Performance', 20, 120);
      
      doc.setFontSize(10);
      doc.setTextColor(0, 0, 0);
      
      let yPos = 130;
      students.slice(0, 20).forEach((student, index) => {
        if (yPos > 270) {
          doc.addPage();
          yPos = 20;
        }
        
        const avgMastery = student.levelProgress
          ? Math.round(Object.values(student.levelProgress).reduce((sum: number, lp: any) => sum + lp.mastery, 0) / 3)
          : 0;
        
        doc.text(`${index + 1}. ${student.name}`, 20, yPos);
        doc.text(`Sparkies: ${student.sparkies || 0}`, 80, yPos);
        doc.text(`Words: ${student.wordsLearned || 0}`, 120, yPos);
        doc.text(`Mastery: ${avgMastery}%`, 160, yPos);
        
        yPos += 7;
      });
      
      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text('Generated by Mastering Words - Gamified Spelling System', 105, 285, { align: 'center' });
      
      doc.save(`Class_Report_${new Date().toISOString().split('T')[0]}.pdf`);
      alert('✅ Report generated successfully!');
    } catch (error) {
      console.error('Error generating report:', error);
      alert('❌ Failed to generate report. Please try again.');
    }
  };

  const downloadCertificate = (cert: Certificate) => {
    const doc = new jsPDF({
      orientation: 'landscape',
      unit: 'px',
      format: [600, 400]
    });

    // Background - Light cream color
    doc.setFillColor(255, 253, 245);
    doc.rect(0, 0, 600, 400, 'F');

    // Decorative corner stars
    const drawStar = (x: number, y: number, size: number, color: number[]) => {
      doc.setFillColor(color[0], color[1], color[2]);
      doc.setDrawColor(color[0], color[1], color[2]);
      // Simple star using triangles
      const points = [];
      for (let i = 0; i < 5; i++) {
        const angle = (i * 4 * Math.PI) / 5 - Math.PI / 2;
        points.push([x + size * Math.cos(angle), y + size * Math.sin(angle)]);
      }
      doc.triangle(points[0][0], points[0][1], points[2][0], points[2][1], points[4][0], points[4][1], 'F');
      doc.triangle(points[1][0], points[1][1], points[3][0], points[3][1], points[0][0], points[0][1], 'F');
    };

    // Corner decorations - Stars
    drawStar(50, 50, 15, [243, 156, 18]); // Top left - Gold
    drawStar(550, 50, 15, [243, 156, 18]); // Top right - Gold
    drawStar(50, 350, 12, [0, 194, 160]); // Bottom left - Teal
    drawStar(550, 350, 12, [0, 194, 160]); // Bottom right - Teal

    // Additional small stars scattered
    drawStar(100, 80, 8, [255, 215, 0]);
    drawStar(500, 80, 8, [255, 215, 0]);
    drawStar(80, 320, 8, [255, 215, 0]);
    drawStar(520, 320, 8, [255, 215, 0]);

    // Elegant Triple Border
    doc.setDrawColor(0, 194, 160); // Teal outer
    doc.setLineWidth(8);
    doc.rect(15, 15, 570, 370);
    
    doc.setDrawColor(243, 156, 18); // Gold middle
    doc.setLineWidth(3);
    doc.rect(25, 25, 550, 350);
    
    doc.setDrawColor(0, 194, 160); // Teal inner
    doc.setLineWidth(1);
    doc.rect(30, 30, 540, 340);

    // Decorative ribbon banner at top
    doc.setFillColor(0, 194, 160);
    doc.rect(100, 55, 400, 35, 'F');
    doc.setFillColor(0, 180, 150);
    // Ribbon tails
    doc.triangle(100, 55, 100, 90, 80, 72.5, 'F');
    doc.triangle(500, 55, 500, 90, 520, 72.5, 'F');

    // Header with shadow effect
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(28);
    doc.text('CERTIFICATE OF MASTERY', 300, 78, { align: 'center' });

    // Subheader
    doc.setTextColor(100, 116, 139);
    doc.setFontSize(12);
    doc.text('Mastering Words: A Gamified Spelling Learning System', 300, 115, { align: 'center' });

    // Decorative line
    doc.setDrawColor(243, 156, 18);
    doc.setLineWidth(2);
    doc.line(150, 125, 450, 125);

    // Body
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.text('This proudly confirms that', 300, 155, { align: 'center' });

    // Student name with decorative underline
    doc.setFontSize(32);
    doc.setTextColor(243, 156, 18);
    doc.text(cert.userName.toUpperCase(), 300, 195, { align: 'center' });
    
    // Decorative underline for name
    doc.setDrawColor(243, 156, 18);
    doc.setLineWidth(1);
    const nameWidth = doc.getTextWidth(cert.userName.toUpperCase());
    doc.line(300 - nameWidth/2 - 20, 205, 300 + nameWidth/2 + 20, 205);

    // Achievement text
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.text(`has successfully mastered the`, 300, 235, { align: 'center' });
    
    doc.setFontSize(20);
    doc.setTextColor(0, 194, 160);
    doc.text(`${cert.title}`, 300, 260, { align: 'center' });

    // Large decorative star in center background
    doc.setGState(new doc.GState({ opacity: 0.05 }));
    drawStar(300, 200, 80, [243, 156, 18]);
    doc.setGState(new doc.GState({ opacity: 1 }));

    // Trophy/Medal icon - Draw a trophy shape
    // Trophy cup (main circle)
    doc.setFillColor(255, 215, 0);
    doc.circle(300, 295, 30, 'F');
    doc.setFillColor(243, 156, 18);
    doc.circle(300, 295, 25, 'F');
    
    // Trophy handles (using ellipses)
    doc.setFillColor(255, 215, 0);
    doc.ellipse(275, 290, 6, 10, 'F');
    doc.ellipse(325, 290, 6, 10, 'F');
    
    // Trophy base
    doc.setFillColor(255, 215, 0);
    doc.rect(290, 310, 20, 3, 'F');
    doc.rect(285, 313, 30, 5, 'F');
    
    // Trophy inner detail
    doc.setFillColor(255, 215, 0);
    doc.circle(300, 295, 15, 'F');

    // Footer Info without emojis
    doc.setTextColor(100, 116, 139);
    doc.setFontSize(11);
    doc.text(`Earned: ${cert.earnedDate}`, 60, 345);
    doc.text(`Authorized by: ${cert.teacherName || 'The Word Master AI'}`, 340, 345);

    // Official Seal with ribbon - Improved design
    doc.setDrawColor(243, 156, 18);
    doc.setFillColor(243, 156, 18);
    doc.circle(520, 310, 28, 'F');
    doc.setFillColor(255, 215, 0);
    doc.circle(520, 310, 24, 'F');
    
    // Inner circle for seal
    doc.setDrawColor(243, 156, 18);
    doc.setLineWidth(2);
    doc.circle(520, 310, 18);
    
    doc.setTextColor(243, 156, 18);
    doc.setFontSize(8);
    doc.text('OFFICIAL', 520, 306, { align: 'center' });
    doc.text('SEAL', 520, 316, { align: 'center' });
    
    // Seal ribbons
    doc.setFillColor(220, 53, 69);
    doc.rect(515, 335, 10, 25, 'F');
    doc.triangle(515, 360, 520, 365, 525, 360, 'F');

    // Sparkles around seal - Draw as stars instead of emoji
    const drawSmallStar = (x: number, y: number) => {
      doc.setFillColor(255, 215, 0);
      const size = 4;
      const points = [];
      for (let i = 0; i < 5; i++) {
        const angle = (i * 4 * Math.PI) / 5 - Math.PI / 2;
        points.push([x + size * Math.cos(angle), y + size * Math.sin(angle)]);
      }
      doc.triangle(points[0][0], points[0][1], points[2][0], points[2][1], points[4][0], points[4][1], 'F');
      doc.triangle(points[1][0], points[1][1], points[3][0], points[3][1], points[0][0], points[0][1], 'F');
    };
    
    drawSmallStar(490, 300);
    drawSmallStar(550, 300);
    drawSmallStar(505, 330);
    drawSmallStar(535, 330);

    doc.save(`${cert.userName}_Mastery_Certificate_${cert.difficulty}.pdf`);
  };

  return (
    <div className="space-y-10 animate-in fade-in slide-in-from-bottom-4 duration-500 pb-20">
      {/* Profile Header */}
      <div className="bg-gradient-to-br from-[#162031] to-[#1a2942] rounded-[2.5rem] p-10 text-center shadow-2xl border border-white/10 relative overflow-hidden">
        {/* Decorative background elements */}
        <div className="absolute top-0 right-0 w-40 h-40 bg-[#00c2a0]/5 rounded-full blur-3xl" />
        <div className="absolute bottom-0 left-0 w-40 h-40 bg-[#f39c12]/5 rounded-full blur-3xl" />
        
        <div className="relative z-10">
          <div className="relative inline-block mb-6">
            <div className="w-28 h-28 bg-gradient-to-br from-[#00c2a0] to-[#00d8b3] rounded-full flex items-center justify-center text-white text-5xl font-bold ring-8 ring-[#0c1322] shadow-2xl">
              {user.name[0].toUpperCase()}
            </div>
            <div className="absolute bottom-0 right-0 bg-gradient-to-br from-[#f39c12] to-[#e67e22] w-10 h-10 rounded-full border-4 border-[#162031] flex items-center justify-center text-lg shadow-lg">
              {user.role === UserRole.TEACHER ? '👨‍🏫' : user.role === UserRole.ADMIN ? '👑' : '✏️'}
            </div>
          </div>
          
          <h2 className="text-4xl font-bold text-white mb-2">
            {user.name}
          </h2>
          <p className="text-gray-400 mb-1 text-lg">{user.username ? `@${user.username}` : user.email}</p>
          
          {user.role === UserRole.STUDENT && user.gradeLevel && user.section && (
            <div className="inline-flex items-center gap-2 bg-[#00c2a0]/10 border border-[#00c2a0]/30 px-4 py-2 rounded-full mt-2 mb-6">
              <span className="text-[#00c2a0] font-bold text-sm">
                📚 Grade {user.gradeLevel} • Section {user.section}
              </span>
            </div>
          )}
          
          {user.subject && (
            <p className="text-[#00c2a0] text-sm font-bold mb-8">📚 {user.subject}</p>
          )}

          {/* Stats for Students */}
          {user.role === UserRole.STUDENT && (
            <div className="grid grid-cols-3 gap-6 pt-8 border-t border-white/10 mb-8">
              <div className="relative group">
                <div className="absolute inset-0 bg-gradient-to-br from-[#f39c12]/20 to-transparent rounded-2xl blur-xl opacity-0 group-hover:opacity-100 transition-opacity" />
                <div className="relative bg-[#0c1322]/50 backdrop-blur-sm rounded-2xl p-4 border border-white/5">
                  <span className="text-[#f39c12] text-3xl block mb-2">✨</span>
                  <p className="text-3xl font-bold text-white mb-1">{user.sparkies || 0}</p>
                  <p className="text-xs uppercase font-bold text-gray-400 tracking-wider">Sparkies</p>
                </div>
              </div>
              
              <div className="relative group">
                <div className="absolute inset-0 bg-gradient-to-br from-blue-500/20 to-transparent rounded-2xl blur-xl opacity-0 group-hover:opacity-100 transition-opacity" />
                <div className="relative bg-[#0c1322]/50 backdrop-blur-sm rounded-2xl p-4 border border-white/5">
                  <span className="text-blue-500 text-3xl block mb-2">🎓</span>
                  <p className="text-3xl font-bold text-white mb-1">{user.wordsLearned || 0}</p>
                  <p className="text-xs uppercase font-bold text-gray-400 tracking-wider">Words</p>
                </div>
              </div>
              
              <div className="relative group">
                <div className="absolute inset-0 bg-gradient-to-br from-red-500/20 to-transparent rounded-2xl blur-xl opacity-0 group-hover:opacity-100 transition-opacity" />
                <div className="relative bg-[#0c1322]/50 backdrop-blur-sm rounded-2xl p-4 border border-white/5">
                  <span className="text-red-500 text-3xl block mb-2">🔥</span>
                  <p className="text-3xl font-bold text-white mb-1">{user.longestStreak || 0}</p>
                  <p className="text-xs uppercase font-bold text-gray-400 tracking-wider">Best Streak</p>
                </div>
              </div>
            </div>
          )}

          {/* Stats for Teachers */}
          {user.role === UserRole.TEACHER && (
            <div className="grid grid-cols-3 gap-4 pt-6 border-t border-white/5 mb-8">
              <div>
                <span className="text-[#00c2a0] text-2xl block mb-1">👥</span>
                <p className="text-xl font-bold text-white">{loading ? '...' : stats.totalStudents}</p>
                <p className="text-[10px] uppercase font-bold text-gray-500 tracking-tighter">Students</p>
              </div>
              <div>
                <span className="text-[#f39c12] text-2xl block mb-1">📚</span>
                <p className="text-xl font-bold text-white">{loading ? '...' : stats.totalWords}</p>
                <p className="text-[10px] uppercase font-bold text-gray-500 tracking-tighter">Words</p>
              </div>
              <div>
                <span className="text-blue-500 text-2xl block mb-1">🎮</span>
                <p className="text-xl font-bold text-white">{loading ? '...' : stats.totalGamesPlayed}</p>
                <p className="text-[10px] uppercase font-bold text-gray-500 tracking-tighter">Games</p>
              </div>
            </div>
          )}

          <button 
            onClick={onLogout}
            className="text-red-400 font-bold uppercase tracking-widest text-sm hover:bg-red-500/10 px-10 py-4 rounded-2xl transition-all border-2 border-red-500/30 hover:border-red-500/50 active:scale-95"
          >
            Sign Out
          </button>
        </div>
      </div>

      {/* Teacher-Specific Content */}
      {user.role === UserRole.TEACHER && !loading && (
        <>
          {/* Class Overview */}
          <section>
            <h3 className="text-2xl font-bold text-white mb-6">Class Overview</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Active Students Card */}
              <div className="bg-gradient-to-br from-[#00c2a0]/10 to-[#00c2a0]/5 border border-[#00c2a0]/20 rounded-2xl p-6">
                <div className="flex items-center justify-between mb-4">
                  <div className="w-12 h-12 bg-[#00c2a0]/20 rounded-xl flex items-center justify-center text-2xl">
                    ✅
                  </div>
                  <span className="text-xs font-bold text-[#00c2a0] uppercase">Engagement</span>
                </div>
                <p className="text-3xl font-bold text-white mb-1">{stats.activeStudents}</p>
                <p className="text-sm text-gray-400">Active Students</p>
                <div className="mt-4 pt-4 border-t border-white/5">
                  <p className="text-xs text-gray-500">
                    {stats.totalStudents > 0 
                      ? `${Math.round((stats.activeStudents / stats.totalStudents) * 100)}% of class is active`
                      : 'No students yet'}
                  </p>
                </div>
              </div>

              {/* Average Progress Card */}
              <div className="bg-gradient-to-br from-blue-500/10 to-blue-500/5 border border-blue-500/20 rounded-2xl p-6">
                <div className="flex items-center justify-between mb-4">
                  <div className="w-12 h-12 bg-blue-500/20 rounded-xl flex items-center justify-center text-2xl">
                    📊
                  </div>
                  <span className="text-xs font-bold text-blue-400 uppercase">Progress</span>
                </div>
                <p className="text-3xl font-bold text-white mb-1">{stats.avgClassProgress}%</p>
                <p className="text-sm text-gray-400">Average Class Mastery</p>
                <div className="mt-4 pt-4 border-t border-white/5">
                  <div className="w-full h-2 bg-[#0b1221] rounded-full overflow-hidden">
                    <div 
                      className="h-full bg-blue-500 transition-all duration-1000"
                      style={{ width: `${stats.avgClassProgress}%` }}
                    />
                  </div>
                </div>
              </div>

              {/* Words Created Card */}
              <div className="bg-gradient-to-br from-[#f39c12]/10 to-[#f39c12]/5 border border-[#f39c12]/20 rounded-2xl p-6">
                <div className="flex items-center justify-between mb-4">
                  <div className="w-12 h-12 bg-[#f39c12]/20 rounded-xl flex items-center justify-center text-2xl">
                    ✍️
                  </div>
                  <span className="text-xs font-bold text-[#f39c12] uppercase">Content</span>
                </div>
                <p className="text-3xl font-bold text-white mb-1">{stats.wordsCreated}</p>
                <p className="text-sm text-gray-400">Words Created</p>
                <div className="mt-4 pt-4 border-t border-white/5">
                  <p className="text-xs text-gray-500">
                    {stats.totalWords > 0 
                      ? `${Math.round((stats.wordsCreated / stats.totalWords) * 100)}% of total word bank`
                      : 'Start creating words!'}
                  </p>
                </div>
              </div>

              {/* Total Games Card */}
              <div className="bg-gradient-to-br from-purple-500/10 to-purple-500/5 border border-purple-500/20 rounded-2xl p-6">
                <div className="flex items-center justify-between mb-4">
                  <div className="w-12 h-12 bg-purple-500/20 rounded-xl flex items-center justify-center text-2xl">
                    🎮
                  </div>
                  <span className="text-xs font-bold text-purple-400 uppercase">Activity</span>
                </div>
                <p className="text-3xl font-bold text-white mb-1">{stats.totalGamesPlayed}</p>
                <p className="text-sm text-gray-400">Total Games Played</p>
                <div className="mt-4 pt-4 border-t border-white/5">
                  <p className="text-xs text-gray-500">
                    {stats.totalStudents > 0 
                      ? `${Math.round(stats.totalGamesPlayed / stats.totalStudents)} games per student`
                      : 'Waiting for students to play'}
                  </p>
                </div>
              </div>
            </div>
          </section>

          {/* Quick Actions */}
          <section>
            <h3 className="text-2xl font-bold text-white mb-6">Quick Actions</h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <button 
                onClick={() => onNavigate?.('students')}
                className="bg-[#162031] hover:bg-[#1a2638] border border-white/5 rounded-2xl p-6 text-left transition-all group active:scale-95"
              >
                <div className="w-12 h-12 bg-[#00c2a0]/20 rounded-xl flex items-center justify-center text-2xl mb-4 group-hover:scale-110 transition-transform">
                  👥
                </div>
                <h4 className="text-white font-bold mb-2">View All Students</h4>
                <p className="text-gray-500 text-sm">Monitor student progress and performance</p>
              </button>

              <button 
                onClick={() => onNavigate?.('words')}
                className="bg-[#162031] hover:bg-[#1a2638] border border-white/5 rounded-2xl p-6 text-left transition-all group active:scale-95"
              >
                <div className="w-12 h-12 bg-[#f39c12]/20 rounded-xl flex items-center justify-center text-2xl mb-4 group-hover:scale-110 transition-transform">
                  📚
                </div>
                <h4 className="text-white font-bold mb-2">Manage Word Bank</h4>
                <p className="text-gray-500 text-sm">Add, edit, or organize spelling words</p>
              </button>

              <button 
                onClick={generateClassReport}
                className="bg-[#162031] hover:bg-[#1a2638] border border-white/5 rounded-2xl p-6 text-left transition-all group active:scale-95"
              >
                <div className="w-12 h-12 bg-purple-500/20 rounded-xl flex items-center justify-center text-2xl mb-4 group-hover:scale-110 transition-transform">
                  📊
                </div>
                <h4 className="text-white font-bold mb-2">Generate Report</h4>
                <p className="text-gray-500 text-sm">Export class performance data</p>
              </button>
            </div>
          </section>

          {/* Teaching Tips */}
          <section>
            <h3 className="text-2xl font-bold text-white mb-6">Teaching Tips</h3>
            <div className="bg-[#162031] rounded-2xl p-6 border border-white/5 space-y-4">
              <div className="flex items-start gap-4">
                <div className="w-10 h-10 bg-[#00c2a0]/20 rounded-xl flex items-center justify-center text-xl flex-shrink-0">
                  💡
                </div>
                <div>
                  <h4 className="text-white font-bold mb-1">Assign Grade-Specific Words</h4>
                  <p className="text-gray-400 text-sm">Use the grade level and section filters when creating words to ensure age-appropriate content for each class.</p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <div className="w-10 h-10 bg-blue-500/20 rounded-xl flex items-center justify-center text-xl flex-shrink-0">
                  🎯
                </div>
                <div>
                  <h4 className="text-white font-bold mb-1">Monitor Student Progress</h4>
                  <p className="text-gray-400 text-sm">Check the Students tab regularly to identify students who need extra support or are ready for more challenging words.</p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <div className="w-10 h-10 bg-[#f39c12]/20 rounded-xl flex items-center justify-center text-xl flex-shrink-0">
                  ⚡
                </div>
                <div>
                  <h4 className="text-white font-bold mb-1">Use AI Word Generation</h4>
                  <p className="text-gray-400 text-sm">Save time by using the AI Word Generator to create themed word sets quickly and efficiently.</p>
                </div>
              </div>

              <div className="flex items-start gap-4">
                <div className="w-10 h-10 bg-purple-500/20 rounded-xl flex items-center justify-center text-xl flex-shrink-0">
                  🏆
                </div>
                <div>
                  <h4 className="text-white font-bold mb-1">Celebrate Achievements</h4>
                  <p className="text-gray-400 text-sm">Recognize students who earn certificates and maintain streaks to encourage continued engagement.</p>
                </div>
              </div>
            </div>
          </section>

          {/* Account Information */}
          <section>
            <h3 className="text-2xl font-bold text-white mb-6">Account Information</h3>
            <div className="bg-[#162031] rounded-2xl p-6 border border-white/5 space-y-4">
              <div className="flex justify-between items-center py-3 border-b border-white/5">
                <span className="text-gray-400 text-sm">Role</span>
                <span className="text-white font-bold">Teacher</span>
              </div>
              <div className="flex justify-between items-center py-3 border-b border-white/5">
                <span className="text-gray-400 text-sm">Email</span>
                <span className="text-white font-bold">{user.email}</span>
              </div>
              <div className="flex justify-between items-center py-3 border-b border-white/5">
                <span className="text-gray-400 text-sm">Username</span>
                <span className="text-white font-bold">@{user.username}</span>
              </div>
              {user.subject && (
                <div className="flex justify-between items-center py-3 border-b border-white/5">
                  <span className="text-gray-400 text-sm">Subject</span>
                  <span className="text-white font-bold">{user.subject}</span>
                </div>
              )}
              <div className="flex justify-between items-center py-3">
                <span className="text-gray-400 text-sm">Account Type</span>
                <span className="text-[#00c2a0] font-bold">Professional</span>
              </div>
            </div>
          </section>
        </>
      )}

      {/* Student-Specific Content */}
      {user.role === UserRole.STUDENT && (
        <>
          <section>
            <h3 className="text-2xl font-bold text-white mb-6">Certificates of Mastery</h3>
            {user.certificates && user.certificates.length > 0 ? (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {user.certificates.map(cert => (
                  <div key={cert.id} className="bg-[#162031] p-6 rounded-[2rem] border border-[#f39c12]/20 flex flex-col shadow-xl animate-in zoom-in duration-300">
                    <div className="flex items-center gap-4 mb-4">
                      <div className="w-14 h-14 bg-[#f39c12]/10 rounded-2xl flex items-center justify-center text-3xl">📜</div>
                      <div>
                        <h4 className="text-white font-bold text-lg">{cert.title}</h4>
                        <p className="text-gray-500 text-xs">Earned on {cert.earnedDate}</p>
                      </div>
                    </div>
                    <button 
                      onClick={() => downloadCertificate(cert)}
                      className="w-full mt-auto bg-[#00c2a0] hover:bg-[#00d8b3] text-white font-bold py-3 rounded-xl text-xs uppercase tracking-widest transition-all shadow-lg active:scale-95"
                    >
                      Download PDF 📥
                    </button>
                  </div>
                ))}
              </div>
            ) : (
              <div className="bg-[#162031] p-8 rounded-[2rem] text-center border border-white/5 opacity-50 italic text-gray-500">
                Master a level with 100% score to earn your first certificate!
              </div>
            )}
          </section>

          <section>
            <div className="flex justify-between items-end mb-6">
              <h3 className="text-2xl font-bold text-white">Badges ({user.badges?.length || 0}/{BADGES.length})</h3>
            </div>
            <div className="grid grid-cols-3 md:grid-cols-5 gap-4">
              {BADGES.map((badge, index) => {
                const isUnlocked = user.badges?.includes(badge.id);
                return (
                  <div 
                    key={badge.id} 
                    className={`aspect-square bg-gradient-to-br rounded-3xl flex flex-col items-center justify-center p-4 text-center transition-all duration-500 transform hover:scale-105 ${
                      isUnlocked 
                        ? 'from-[#162031] to-[#1a2942] border-2 border-[#f39c12] shadow-xl shadow-[#f39c12]/20 animate-in zoom-in' 
                        : 'from-[#0b1221] to-[#162031] opacity-40 grayscale border border-white/5'
                    }`}
                    style={{ animationDelay: `${index * 50}ms` }}
                  >
                    {isUnlocked && (
                      <div className="absolute inset-0 rounded-3xl bg-gradient-to-br from-[#f39c12]/10 to-transparent animate-pulse" />
                    )}
                    <div className={`text-4xl mb-2 relative z-10 ${isUnlocked ? 'animate-bounce' : ''}`}>
                      {isUnlocked ? badge.icon : '🔒'}
                    </div>
                    <p className={`text-[10px] font-bold leading-tight relative z-10 ${isUnlocked ? 'text-white' : 'text-gray-600'}`}>
                      {badge.name}
                    </p>
                    {isUnlocked && (
                      <div className="absolute top-2 right-2 w-3 h-3 bg-[#00c2a0] rounded-full animate-ping" />
                    )}
                  </div>
                );
              })}
            </div>
          </section>

          <section>
            <h3 className="text-2xl font-bold text-white mb-6">Achievements ({user.achievements?.length || 0}/{ACHIEVEMENTS.length})</h3>
            <div className="space-y-4">
              {ACHIEVEMENTS.map(ach => {
                const isUnlocked = user.achievements?.includes(ach.id);
                return (
                  <div key={ach.id} className={`bg-[#162031] p-6 rounded-3xl flex items-center gap-6 border transition-all ${isUnlocked ? 'border-[#00c2a0]/40 opacity-100' : 'border-white/5 opacity-40'}`}>
                    <div className={`w-14 h-14 rounded-2xl flex items-center justify-center text-2xl ${isUnlocked ? 'bg-[#00c2a0]/20' : 'bg-[#0c1322]'}`}>
                      {isUnlocked ? ach.icon : '🔒'}
                    </div>
                    <div className="flex-1">
                      <h4 className={`font-bold text-lg mb-1 ${isUnlocked ? 'text-white' : 'text-gray-500'}`}>{ach.name}</h4>
                      <p className="text-gray-500 text-sm">{ach.description}</p>
                    </div>
                    {isUnlocked && <span className="text-[#00c2a0] font-bold text-xs uppercase tracking-widest">Unlocked</span>}
                  </div>
                );
              })}
            </div>
          </section>
        </>
      )}
    </div>
  );
};

export default ProfileView;
